# Generated by Django 4.0.4 on 2022-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment01', '0002_buyerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=32, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=32, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='buyerinfo',
            name='address',
            field=models.CharField(max_length=64, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='buyerinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='buyerinfo',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='phone'),
        ),
    ]
