# Generated by Django 4.0.4 on 2022-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment01', '0004_equipment_info_delete_buyerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_info',
            name='number',
            field=models.CharField(default='', max_length=32, verbose_name='编号'),
        ),
    ]
