# Generated by Django 4.0.4 on 2022-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment01', '0005_equipment_info_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toberepaired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('number', models.CharField(default='', max_length=32, verbose_name='编号')),
                ('date', models.DateTimeField(verbose_name='修理日期')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='修理厂家')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='修理单价')),
                ('responsible', models.CharField(max_length=32, verbose_name='责任人')),
            ],
        ),
    ]
