# Generated by Django 4.0.4 on 2022-05-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment01', '0006_toberepaired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toberepaired',
            name='name',
        ),
    ]
